### ISSUE TITLE
Low Pass Filter is not implemented?

### ISSUE THREAD

**Issue by yuhang-lin** [phishman3579/android-compass#1]
LowPassFilter is created but not implemented.

**Comment by phishman3579** [comment]
Not sure what you mean, the implementation is here:
https://github.com/phishman3579/android-compass/blob/master/src/com/jwetherell/compass/common/LowPassFilter.java

**Comment by yuhang-lin** [comment]
There is a private function LowPassFilter(), but it's empty.

**Comment by phishman3579** [comment]
It's a public static function.
public static float[] filter(float[] input, float[] prev)

**Comment by yuhang-lin** [comment]
Oh sorry I didn't realize that private function is actually the constructor of the class.
